### ISSUE TITLE
Unit tests failing when running the CI locally (in a VM)

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/runtime#772]
# Description of problem

When running the CI scripts locally (not on Azure VMs) @mcastelino found this issue, which I could reproduce later with the latest changes in master. 

# Expected result

All unit tests should pass. 

# Actual result

Got the errors described below. The question here is why these tests are passing on Azure and not when running locally.
Logs:

```
fuentess@singlevm:~/go/src/github.com/clearcontainers/runtime$ .ci/run.sh
     CHECK   check-go-static
Updating gocyclo...
Updating misspell...
Updating golint...
Updating ineffassign...
Doing go static checks on packages: github.com/clearcontainers/runtime
Running misspell...
Running go vet...
Running gofmt...
Running cyclo...
Running golint...
Running ineffassign...
All Good!
     CHECK   check-go-static
     TEST    check-go-test
INFO: switching to fake virtcontainers implementation for testing
INFO: creating test directory
INFO: test directory is /tmp/cc-runtime-478024666
INFO: ensuring required docker image (busybox) is available
panic: exit status 1

goroutine 1 [running, locked to thread]:
panic(0xc87320, 0xc420152240)
        /usr/local/go/src/runtime/panic.go:531 +0x1de fp=0xc420105cd0 sp=0xc420105c38
github.com/clearcontainers/runtime.init.3()
        /home/fuentess/go/src/github.com/clearcontainers/runtime/main_test.go:114 +0x56d fp=0xc420105e98 sp=0xc420105cd0
github.com/clearcontainers/runtime.init()
        /home/fuentess/go/src/github.com/clearcontainers/runtime/version_test.go:66 +0x10d3 fp=0xc420105f78 sp=0xc420105e98
main.init()
        github.com/clearcontainers/runtime/_test/_testmain.go:522 +0xaa fp=0xc420105f90 sp=0xc420105f78
runtime.main()
        /usr/local/go/src/runtime/proc.go:173 +0x163 fp=0xc420105fe0 sp=0xc420105f90
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420105fe8 sp=0xc420105fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420040fe8 sp=0xc420040fe0

goroutine 2 [force gc (idle)]:
runtime.gopark(0xcd4928, 0x1228280, 0xcb57bc, 0xf, 0x43f014, 0x1)
        /usr/local/go/src/runtime/proc.go:271 +0xfd fp=0xc42002e768 sp=0xc42002e738
runtime.goparkunlock(0x1228280, 0xcb57bc, 0xf, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:277 +0x5e fp=0xc42002e7a8 sp=0xc42002e768
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:226 +0x9e fp=0xc42002e7e0 sp=0xc42002e7a8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42002e7e8 sp=0xc42002e7e0
created by runtime.init.4
        /usr/local/go/src/runtime/proc.go:215 +0x35

goroutine 18 [GC sweep wait]:
runtime.gopark(0xcd4928, 0x12284e0, 0xcb3ea9, 0xd, 0x42fe14, 0x1)
        /usr/local/go/src/runtime/proc.go:271 +0xfd fp=0xc42002a758 sp=0xc42002a728
runtime.goparkunlock(0x12284e0, 0xcb3ea9, 0xd, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:277 +0x5e fp=0xc42002a798 sp=0xc42002a758
runtime.bgsweep(0xc420072000)
        /usr/local/go/src/runtime/mgcsweep.go:56 +0xb6 fp=0xc42002a7d8 sp=0xc42002a798
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42002a7e0 sp=0xc42002a7d8
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:212 +0x61

goroutine 19 [finalizer wait]:
runtime.gopark(0xcd4928, 0x1bc8198, 0xcb4d51, 0xe, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:271 +0xfd fp=0xc42002af18 sp=0xc42002aee8
runtime.goparkunlock(0x1bc8198, 0xcb4d51, 0xe, 0x14, 0x1)
        /usr/local/go/src/runtime/proc.go:277 +0x5e fp=0xc42002af58 sp=0xc42002af18
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:161 +0xb2 fp=0xc42002afe0 sp=0xc42002af58
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42002afe8 sp=0xc42002afe0
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:142 +0x62
signal: aborted (core dumped)
FAIL    github.com/clearcontainers/runtime      0.114s
Makefile:314: recipe for target 'check-go-test' failed
make: *** [check-go-test] Error 1
```

**Comment by chavafg** [comment]
Info from cc-collect-data.sh:

# Meta details                                                                                                                                                                                           [219/1764]

Running `cc-collect-data.sh` version `3.0.5 (commit 2157c2a007c3bc58edb572523c77b55a9d7fa0b6)` at `2017-10-27.22:54:49.088458177`.

---

Runtime is `/usr/local/bin/cc-runtime`.

# `cc-env`

Output of "`/usr/local/bin/cc-runtime cc-env`":
```
[Meta]
  Version = "1.0.5"

[Runtime]
  [Runtime.Version]
    Semver = "3.0.5"
    Commit = "2157c2a007c3bc58edb572523c77b55a9d7fa0b6"
    OCI = "1.0.0-dev"
  [Runtime.Config]
    Path = "/usr/share/defaults/clear-containers/configuration.toml"
    GlobalLogPath = "/var/lib/clear-containers/runtime/runtime.log"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.7.0, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-lite-system-x86_64"

[Image]
  Path = "/usr/share/clear-containers/clear-18520-containers.img"

[Kernel]
  Path = "/usr/share/clear-containers/vmlinuz-4.9.58-79.container"
  Parameters = ""

[Proxy]
  Type = "ccProxy"
  Version = "Version: 3.0.5"
  URL = "unix:///var/run/clear-containers/proxy.sock"

[Shim]
  Type = "ccShim"
  Version = "shim version: 3.0.5 (commit: 86a7c204b1f7b925a28dc68f919f4df941dcb7d9)"
  Path = "/usr/libexec/clear-containers/cc-shim"


[Agent]
  Type = "hyperstart"
  Version = "<<unknown>>"

[Host]
  Kernel = "4.4.0-87-generic"
  CCCapable = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "16.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz"
```

---


# Runtime config files


## Runtime default config files

```
/etc/clear-containers/configuration.toml
/usr/share/defaults/clear-containers/configuration.toml
```

## Runtime config file contents

Config file `/etc/clear-containers/configuration.toml` not found
Output of "`cat "/usr/share/defaults/clear-containers/configuration.toml"`":
```
# XXX: Warning: this file is auto-generated from file "config/configuration.toml.in".

[hypervisor.qemu]
path = "/usr/bin/qemu-lite-system-x86_64"
kernel = "/usr/share/clear-containers/vmlinuz.container"
image = "/usr/share/clear-containers/clear-containers.img"
machine_type = "pc"
# Optional space-separated list of options to pass to the guest kernel.
# For example, use `kernel_params = "vsyscall=emulate"` if you are having
# trouble running pre-2.15 glibc
kernel_params = ""

# Default number of vCPUs per POD/VM:
# unspecified or 0 --> will be set to 1
# < 0              --> will be set to the actual number of physical cores
# > 0 <= 255       --> will be set to the specified number
# > 255            --> will be set to 255
default_vcpus = -1

# Default memory size in MiB for POD/VM.
# If unspecified then it will be set 2048 MiB.
#default_memory = 2048
disable_block_device_use = false

# Enable pre allocation of VM RAM, default false
# Enabling this will result in lower container density
# as all of the memory will be allocated and locked
# This is useful when you want to reserve all the memory
# upfront or in the cases where you want memory latencies
# to be very predictable
# Default false
#enable_mem_prealloc = true

# Enable huge pages for VM RAM, default false
# Enabling this will result in the VM memory
# being allocated using huge pages.
# This is useful when you want to use vhost-user network
# stacks within the container. This will automatically
# result in memory pre allocation
#enable_hugepages = true

# Enable swap of vm memory. Default false.
# The behaviour is undefined if mem_prealloc is also set to true
#enable_swap = true

# Debug changes the default hypervisor and kernel parameters to
# enable debug output where available.
# Default false
# these logs can be obtained in the cc-proxy logs  when the
# proxy is set to run in debug mode
# /usr/libexec/clear-containers/cc-proxy -log debug
# or by stopping the cc-proxy service and running the cc-proxy
# explicitly using the same command line
#
enable_debug = true

                                                                                                                                                                                                         [85/1764]
# Disable the customizations done in the runtime when it detects
# that it is running on top a VMM. This will result in the runtime
# behaving as it would when running on bare metal.
#
#disable_nesting_checks = true

[proxy.cc]
url = "unix:///var/run/clear-containers/proxy.sock"

[shim.cc]
path = "/usr/libexec/clear-containers/cc-shim"

# If enabled, shim messages will be sent to the system log
# (default: disabled)
enable_debug = true

[agent.hyperstart]
pause_root_path = "@PAUSEROOTPATH@"

[runtime]
## Uncomment to enable the global logging to the default path.
global_log_path = "/var/lib/clear-containers/runtime/runtime.log"

# If enabled, the runtime will log additional debug messages to the global
# log, assuming that is also enabled.
# (default: disabled)
enable_debug = true
```

---


# Logfiles


## Runtime logs

Global log `/var/lib/clear-containers/runtime/runtime.log` does not exist.

## Proxy logs

No recent proxy problems found in system journal.

## Shim logs

No recent shim problems found in system journal.

---


# Container manager details

Have `docker`

## Docker

Output of "`docker info`":
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Swarm: inactive
Runtimes: cc-runtime runc
Default Runtime: cc-runtime
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 2157c2a007c3bc58edb572523c77b55a9d7fa0b6 (expected: 3f2f8b84a77f73d38244dd690525642a72156c64)
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-87-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 6.812GiB
Name: singlevm
ID: TH6Y:LCDJ:454M:H253:AMT2:MRHP:YCTK:HQZA:C2O7:GFVH:ZWE2:25YN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 25
 System Time: 2017-10-27T22:54:49.161056415Z
 EventsListeners: 0
Http Proxy: http://proxy-us.intel.com:911
Https Proxy: http://proxy-us.intel.com:912
No Proxy: singlevm,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16,singlevm
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
No `kubectl`

---


# Packages

Have `dpkg`
Output of "`dpkg -l|egrep "(cc-proxy|cc-runtime|cc-shim|clear-containers-image|linux-container|qemu-lite|qemu-system-x86|cc-oci-runtime)"`":
```
ii  qemu-lite-bin                    741f430a960b5b67745670e8270db91aeb083c5f-30 amd64        bin components for the qemu-lite package.
ii  qemu-lite-data                   741f430a960b5b67745670e8270db91aeb083c5f-30 amd64        data components for the qemu-lite package.
```
Have `rpm`
Output of "`rpm -qa|egrep "(cc-proxy|cc-runtime|cc-shim|clear-containers-image|linux-container|qemu-lite|qemu-system-x86|cc-oci-runtime)"`":
```

```

---

**Comment by jodh-intel** [comment]
@chavafg - I think you'll see this behaviour if docker is either not running, or the current user doesn't have permission to access it (I'll raise a PR to improve the failure behaviour though... :)

**Comment by jodh-intel** [comment]
Improved unit test setup on #775.

**Comment by chavafg** [comment]
oh right, I see that jenkins machines are prepared so the jenkins user can access docker. Then I think we can close this, do you agree @mcastelino ?  

@jodh-intel thanks for the PR, I see that the message of the error is improved:
```
INFO: ensuring docker is running
panic: ERROR: docker daemon is not running: exit status 1
```

**Comment by jodh-intel** [comment]
#777 raised to improve the error yet further ;)

**Comment by mcastelino** [comment]
@jodh-intel @chavafg docker was running on the CI VM. Looks like I need to setup the default user to have docker daemon access. Let me try that.

**Comment by grahamwhaley** [comment]
Its been a bit of a ying yang debate we've never quite formalised - should you have to be in the docker group or should we invoke many things as `sudo` for instance. I probably vote for the former, which seems to be where we are at.

**Comment by chavafg** [comment]
@mcastelino yes, with that it should work, I already tried. or you could also run as `sudo` like @grahamwhaley says. It works both ways.

**Comment by chavafg** [comment]
closing this issue as it was expected to happen and also the error message was improved.
